### ISSUE TITLE
Apply to OpenCL kernel

### ISSUE THREAD

**Issue by GH-Jo** [SKKU-ESLAB/ACL-lowp#2]
Current Lowp gemm in this repository is only applied to NEON kernel.
Mali GPUs are said to be vector processing units so each thread which is running gets SIMD-style instructions.

I suppose that you are able to implement Lowp gemm in OpenCL so that Mali GPUs can run the kernel.

**Comment by RedCarrottt** [comment]
Related to this issue, I think that TVM integration can also include the mobile GPU support. (#9)
In fact, TVM also supports OpenCL backends.

**Comment by LeeHayun** [comment]
> Related to this issue, I think that TVM integration can also include the mobile GPU support. (#9) In fact, TVM also supports OpenCL backends.

You are right.
OpenCL backend work is already in progress through deep learning compiler technology.
So, I close this issue.
